package com.edunexa.app
import android.app.Activity
import android.content.Intent
import android.graphics.*
import android.graphics.drawable.GradientDrawable
import android.net.Uri
import android.os.Bundle
import android.view.View
import android.widget.*
import androidx.appcompat.app.AlertDialog
import androidx.appcompat.app.AppCompatActivity
import java.io.ByteArrayOutputStream
import kotlin.math.ceil
import kotlin.math.max
class ImageMergeActivity:AppCompatActivity(){private lateinit var preview:ImageView;private lateinit var status:TextView;private lateinit var save:Button;private lateinit var layoutText:TextView;private var images=mutableListOf<Bitmap>();private var resultBytes:ByteArray?=null;private var unsaved=false;private var columns=2;private var gap=8;private fun dp(v:Int)=(v*resources.displayMetrics.density).toInt();private fun bg(c:String)=GradientDrawable().apply{setColor(Color.parseColor(c));cornerRadius=dp(16).toFloat()}
override fun onCreate(b:Bundle?){super.onCreate(b);val root=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(dp(18),dp(20),dp(18),dp(30));setBackgroundColor(Color.parseColor("#F6F7FC"))};root.addView(TextView(this).apply{text="Image Merge Studio";textSize=26f;setTypeface(typeface,1);setTextColor(Color.parseColor("#17213D"))});root.addView(TextView(this).apply{text="Select • arrange layout • edit spacing • preview • save";setTextColor(Color.parseColor("#72798F"));setPadding(0,dp(5),0,dp(14))});root.addView(Button(this).apply{text="Select Images";isAllCaps=false;setOnClickListener{startActivityForResult(Intent(Intent.ACTION_OPEN_DOCUMENT).apply{type="image/*";addCategory(Intent.CATEGORY_OPENABLE);putExtra(Intent.EXTRA_ALLOW_MULTIPLE,true)},301)}});root.addView(TextView(this).apply{text="EDIT LAYOUT";setTypeface(typeface,1);setTextColor(Color.parseColor("#3157D5"));setPadding(0,dp(16),0,dp(6))});layoutText=TextView(this).apply{text="Grid: 2 columns • Gap: 8 px"};root.addView(layoutText);val controls=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL};controls.addView(Button(this).apply{text="1 Column";isAllCaps=false;setOnClickListener{columns=1;render()}},LinearLayout.LayoutParams(0,-2,1f));controls.addView(Button(this).apply{text="2 Columns";isAllCaps=false;setOnClickListener{columns=2;render()}},LinearLayout.LayoutParams(0,-2,1f));controls.addView(Button(this).apply{text="3 Columns";isAllCaps=false;setOnClickListener{columns=3;render()}},LinearLayout.LayoutParams(0,-2,1f));root.addView(controls);val seek=SeekBar(this).apply{max=60;progress=8;setOnSeekBarChangeListener(object:SeekBar.OnSeekBarChangeListener{override fun onProgressChanged(s:SeekBar?,p:Int,f:Boolean){gap=p;if(f)render()};override fun onStartTrackingTouch(s:SeekBar?){};override fun onStopTrackingTouch(s:SeekBar?){}})};root.addView(TextView(this).apply{text="Spacing"});root.addView(seek);root.addView(TextView(this).apply{text="LIVE PREVIEW";setTypeface(typeface,1);setTextColor(Color.parseColor("#3157D5"));setPadding(0,dp(12),0,dp(6))});preview=ImageView(this).apply{adjustViewBounds=true;scaleType=ImageView.ScaleType.FIT_CENTER;background=bg("#FFFFFF")};root.addView(preview,LinearLayout.LayoutParams(-1,dp(480)));save=Button(this).apply{text="Save Merged Image";isAllCaps=false;visibility=View.GONE;setOnClickListener{chooseSave()}};root.addView(save);status=TextView(this).apply{text="Nothing is saved until you tap Save.";setPadding(0,dp(10),0,0)};root.addView(status);setContentView(ScrollView(this).apply{addView(root)})}
private fun render(){if(images.size<2)return;columns=columns.coerceAtMost(images.size);val merged=mergeGrid(images,columns,gap);val out=ByteArrayOutputStream();merged.compress(Bitmap.CompressFormat.JPEG,94,out);resultBytes=out.toByteArray();preview.setImageBitmap(merged);save.visibility=View.VISIBLE;unsaved=true;layoutText.text="Grid: $columns column${if(columns>1)"s" else ""} • Gap: $gap px";status.text="${images.size} images • Editable preview ready • ${resultBytes!!.size/1024} KB"}
override fun onActivityResult(req:Int,res:Int,data:Intent?){super.onActivityResult(req,res,data);if(res!=Activity.RESULT_OK)return;if(req==301){val uris=mutableListOf<Uri>();data?.clipData?.let{c->for(i in 0 until c.itemCount)uris.add(c.getItemAt(i).uri)};data?.data?.let{uris.add(it)};images=uris.mapNotNull{u->contentResolver.openInputStream(u)?.use{BitmapFactory.decodeStream(it)}}.toMutableList();if(images.size<2){status.text="Select at least 2 images";return};columns=if(images.size==2)2 else 2;render()}else if(req==302){val uri=data?.data?:return;val bytes=resultBytes?:return;runCatching{contentResolver.openOutputStream(uri)?.use{it.write(bytes)};unsaved=false;status.text="Merged image saved successfully"}.onFailure{status.text="Save failed: ${it.message}"}}}
private fun mergeGrid(src:List<Bitmap>,cols:Int,g:Int):Bitmap{val rows=ceil(src.size.toDouble()/cols).toInt();val cell=600;val out=Bitmap.createBitmap(cell*cols+g*(cols+1),cell*rows+g*(rows+1),Bitmap.Config.ARGB_8888);val c=Canvas(out);c.drawColor(Color.WHITE);src.forEachIndexed{i,b->val scale=max(cell.toFloat()/b.width,cell.toFloat()/b.height);val sw=(b.width*scale).toInt();val sh=(b.height*scale).toInt();val s=Bitmap.createScaledBitmap(b,sw,sh,true);val col=i%cols;val row=i/cols;val l=g+col*(cell+g);val t=g+row*(cell+g);c.save();c.clipRect(l,t,l+cell,t+cell);c.drawBitmap(s,l+(cell-sw)/2f,t+(cell-sh)/2f,null);c.restore()};return out}
private fun chooseSave(){if(resultBytes==null)return;startActivityForResult(Intent(Intent.ACTION_CREATE_DOCUMENT).apply{addCategory(Intent.CATEGORY_OPENABLE);type="image/jpeg";putExtra(Intent.EXTRA_TITLE,"EduNexa_Merge_${System.currentTimeMillis()}.jpg")},302)}
@Suppress("DEPRECATION") override fun onBackPressed(){if(unsaved)AlertDialog.Builder(this).setTitle("Discard merged image?").setMessage("This edited preview has not been saved.").setPositiveButton("Discard"){_,_->unsaved=false;super.onBackPressed()}.setNegativeButton("Stay",null).show()else super.onBackPressed()}}
