package com.edunexa.app
import android.content.Intent
import android.graphics.Color
import android.os.Bundle
import android.text.InputType
import android.view.Gravity
import android.widget.*
import androidx.appcompat.app.AppCompatActivity
import com.edunexa.app.data.ResultRepository
import com.google.android.material.card.MaterialCardView
class MainActivity:AppCompatActivity(){private lateinit var content:FrameLayout;private val results=ResultRepository();private fun dp(v:Int)=(v*resources.displayMetrics.density).toInt();private fun card()=MaterialCardView(this).apply{radius=dp(22).toFloat();cardElevation=dp(3).toFloat();setCardBackgroundColor(Color.WHITE);setContentPadding(dp(18),dp(18),dp(18),dp(18))}
override fun onCreate(b:Bundle?){super.onCreate(b);setContentView(R.layout.activity_main);content=findViewById(R.id.content);findViewById<Button>(R.id.homeBtn).setOnClickListener{showHome()};findViewById<Button>(R.id.toolsBtn).setOnClickListener{showTools()};findViewById<Button>(R.id.connectBtn).setOnClickListener{startActivity(Intent(this,JoinSchoolActivity::class.java))};findViewById<Button>(R.id.profileBtn).setOnClickListener{showHub()};showHome()}
private fun action(r:LinearLayout,t:String,s:String,g:()->Unit){val c=card();val b=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL};b.addView(TextView(this).apply{text=t;textSize=18f;setTypeface(typeface,1)});b.addView(TextView(this).apply{text=s;textSize=14f;setTextColor(Color.GRAY)});c.addView(b);c.setOnClickListener{g()};r.addView(c,LinearLayout.LayoutParams(-1,-2).apply{setMargins(0,0,0,dp(11))})}
private fun showHome(){content.removeAllViews();val r=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL};r.addView(TextView(this).apply{text="Hi, Student 👋";textSize=25f;setTypeface(typeface,1)});r.addView(TextView(this).apply{text="Learn • Calculate • Connect • Grow";setTextColor(Color.GRAY);setPadding(0,dp(4),0,dp(16))});val c=card();val b=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL};b.addView(TextView(this).apply{text="Result Calculator";textSize=21f;setTypeface(typeface,1)});val a=EditText(this).apply{hint="Obtained marks";inputType=2};val z=EditText(this).apply{hint="Total marks";inputType=2};val out=TextView(this).apply{textSize=23f;gravity=Gravity.CENTER};b.addView(a);b.addView(z);b.addView(Button(this).apply{text="Calculate & Save";setOnClickListener{val x=a.text.toString().toDoubleOrNull();val y=z.text.toString().toDoubleOrNull();if(x==null||y==null||y<=0||x<0||x>y){out.text="Enter valid marks"}else{val p=x/y*100;val g=when{p>=90->"A+";p>=80->"A";p>=70->"B";p>=60->"C";p>=45->"D";p>=33->"E";else->"F"};out.text="%.2f%% • Grade %s".format(p,g);results.save(x,y,p,g){_,m->Toast.makeText(this@MainActivity,m,0).show()}}}});b.addView(out);c.addView(b);r.addView(c);action(r,"📝 MCQ Tests","Take school tests"){startActivity(Intent(this,StudentMcqActivity::class.java))};action(r,"📊 School Results","View results published by your school"){startActivity(Intent(this,StudentResultsActivity::class.java))};action(r,"📅 My Attendance","View attendance history and percentage"){startActivity(Intent(this,StudentAttendanceActivity::class.java))};action(r,"📢 Notices","School announcements"){startActivity(Intent(this,NoticeActivity::class.java))};action(r,"🏫 Connect School","Join using EduNexa School Code"){startActivity(Intent(this,JoinSchoolActivity::class.java))};content.addView(ScrollView(this).apply{addView(r)})}
private fun showHub(){content.removeAllViews();val r=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL};r.addView(TextView(this).apply{text="Student Hub";textSize=25f;setTypeface(typeface,1)});action(r,"📊 Calculator History","Saved percentage results"){showHistory()};action(r,"🏆 MCQ History","Completed test scores"){startActivity(Intent(this,McqHistoryActivity::class.java))};action(r,"📚 Published Results","Official school results"){startActivity(Intent(this,StudentResultsActivity::class.java))};action(r,"📅 Attendance","Attendance history"){startActivity(Intent(this,StudentAttendanceActivity::class.java))};action(r,"📢 Notices","School updates"){startActivity(Intent(this,NoticeActivity::class.java))};content.addView(ScrollView(this).apply{addView(r)})}
private fun showHistory(){content.removeAllViews();val r=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL};val s=TextView(this).apply{text="Loading…"};r.addView(s);results.history({rows->s.text=if(rows.isEmpty())"No saved results" else "${rows.size} saved result(s)";rows.forEach{m->val c=card();c.addView(TextView(this).apply{text="${m["percentage"]}% • Grade ${m["grade"]}\n${m["obtained"]} / ${m["total"]}"});r.addView(c)}},{s.text=it});content.addView(ScrollView(this).apply{addView(r)})}
private fun showTools(){content.removeAllViews();val r=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL};r.addView(TextView(this).apply{text="Student Tools";textSize=25f;setTypeface(typeface,1)});arrayOf("Image Resize","Image Compress","Image Merge","Background Remover","PDF Tools","Image ↔ PDF").forEach{n->val c=card();c.addView(TextView(this).apply{text=n;textSize=17f});r.addView(c)};content.addView(ScrollView(this).apply{addView(r)})}}
