package com.edunexa.app
import android.content.Intent
import android.graphics.Color
import android.os.Bundle
import android.view.Gravity
import android.widget.*
import androidx.appcompat.app.AppCompatActivity
import com.edunexa.app.data.ResultRepository
import com.google.android.material.card.MaterialCardView
class MainActivity:AppCompatActivity(){private lateinit var content:FrameLayout;private val results=ResultRepository();private fun dp(v:Int)=(v*resources.displayMetrics.density).toInt();private fun card()=MaterialCardView(this).apply{radius=dp(22).toFloat();cardElevation=dp(3).toFloat();setCardBackgroundColor(Color.WHITE);setContentPadding(dp(18),dp(18),dp(18),dp(18))}
override fun onCreate(b:Bundle?){super.onCreate(b);setContentView(R.layout.activity_main);content=findViewById(R.id.content);findViewById<Button>(R.id.homeBtn).setOnClickListener{showHome()};findViewById<Button>(R.id.toolsBtn).setOnClickListener{showTools()};findViewById<Button>(R.id.connectBtn).setOnClickListener{startActivity(Intent(this,JoinSchoolActivity::class.java))};findViewById<Button>(R.id.profileBtn).setOnClickListener{showHub()};showHome()}
private fun action(r:LinearLayout,t:String,s:String,g:()->Unit){val c=card();val b=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL};b.addView(TextView(this).apply{text=t;textSize=18f;setTypeface(typeface,1)});b.addView(TextView(this).apply{text=s;textSize=14f;setTextColor(Color.GRAY)});c.addView(b);c.setOnClickListener{g()};r.addView(c,LinearLayout.LayoutParams(-1,-2).apply{setMargins(0,0,0,dp(11))})}
private fun showHome(){content.removeAllViews();val r=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL};r.addView(TextView(this).apply{text="Hi, Student 👋";textSize=25f;setTypeface(typeface,1)});r.addView(TextView(this).apply{text="Learn • Calculate • Connect • Grow";setTextColor(Color.GRAY)});action(r,"📝 MCQ Tests","Take school tests"){startActivity(Intent(this,StudentMcqActivity::class.java))};action(r,"📊 School Results","Published school results"){startActivity(Intent(this,StudentResultsActivity::class.java))};action(r,"📅 My Attendance","Attendance history"){startActivity(Intent(this,StudentAttendanceActivity::class.java))};action(r,"📢 Notices","School announcements"){startActivity(Intent(this,NoticeActivity::class.java))};action(r,"🏫 Connect School","Join with School Code"){startActivity(Intent(this,JoinSchoolActivity::class.java))};content.addView(ScrollView(this).apply{addView(r)})}
private fun showHub(){content.removeAllViews();val r=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL};r.addView(TextView(this).apply{text="Student Hub";textSize=25f;setTypeface(typeface,1)});action(r,"🏆 MCQ History","Completed scores"){startActivity(Intent(this,McqHistoryActivity::class.java))};action(r,"📚 Published Results","Official results"){startActivity(Intent(this,StudentResultsActivity::class.java))};action(r,"📅 Attendance","Attendance history"){startActivity(Intent(this,StudentAttendanceActivity::class.java))};content.addView(ScrollView(this).apply{addView(r)})}
private fun showTools(){content.removeAllViews();val r=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL};r.addView(TextView(this).apply{text="EduNexa Tools";textSize=25f;setTypeface(typeface,1)});r.addView(TextView(this).apply{text="Student & Cyber-Café Toolkit";setTextColor(Color.GRAY);setPadding(0,dp(4),0,dp(14))});action(r,"🪪 Exam Form Photo & Signature Maker","Prepare form-ready photo and signature sizes"){startActivity(Intent(this,PhotoSignatureToolActivity::class.java))};action(r,"📐 Target KB Compressor","10KB • 20KB • 50KB • 100KB • Custom"){startActivity(Intent(this,TargetKbToolActivity::class.java))};action(r,"📄 PDF Toolkit","Image→PDF • PDF→Image • Merge • Split"){startActivity(Intent(this,PdfToolkitActivity::class.java))};arrayOf("Image Resize","Image Compress","Image Merge","Background Remover","Image ↔ PDF").forEach{n->action(r,n,"Utility tool"){Toast.makeText(this,"$n processing screen is being completed",Toast.LENGTH_SHORT).show()}};content.addView(ScrollView(this).apply{addView(r)})}}
