package com.edunexa.app

import android.app.Activity
import android.content.Intent
import android.graphics.*
import android.graphics.pdf.PdfDocument
import android.os.Bundle
import android.view.View
import android.widget.*
import androidx.appcompat.app.AlertDialog
import androidx.appcompat.app.AppCompatActivity
import com.google.zxing.BarcodeFormat
import com.google.zxing.qrcode.QRCodeWriter
import java.util.UUID

class MarksheetMakerActivity:AppCompatActivity(){
 private lateinit var school:EditText;private lateinit var address:EditText;private lateinit var student:EditText;private lateinit var roll:EditText;private lateinit var clazz:EditText;private lateinit var exam:EditText;private lateinit var session:EditText;private lateinit var subjects:EditText;private lateinit var preview:ImageView;private lateinit var status:TextView;private lateinit var save:Button
 private var logo:Bitmap?=null;private var sheet:Bitmap?=null;private var unsaved=false
 override fun onCreate(b:Bundle?){super.onCreate(b);val r=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(32,32,32,32)};r.addView(TextView(this).apply{text="Professional Marksheet Maker";textSize=26f;setTypeface(typeface,1)});r.addView(TextView(this).apply{text="School details • Logo • Result • Scannable QR • Preview → Save PDF";setPadding(0,8,0,18)});fun field(h:String)=EditText(this).apply{hint=h;r.addView(this)};school=field("School Name");address=field("School Address / Contact / Code");student=field("Student Name");roll=field("Roll / Admission No.");clazz=field("Class / Section");exam=field("Exam Name");session=field("Academic Session");subjects=field("Subjects: Hindi:100:75, English:100:82, Math:100:90");r.addView(Button(this).apply{text="Choose School Logo";isAllCaps=false;setOnClickListener{startActivityForResult(Intent(Intent.ACTION_OPEN_DOCUMENT).apply{type="image/*";addCategory(Intent.CATEGORY_OPENABLE)},401)}});r.addView(Button(this).apply{text="Generate Preview";isAllCaps=false;setOnClickListener{generate()}});preview=ImageView(this).apply{adjustViewBounds=true;visibility=View.GONE};r.addView(preview,LinearLayout.LayoutParams(-1,900));save=Button(this).apply{text="Save Marksheet PDF";isAllCaps=false;visibility=View.GONE;setOnClickListener{startActivityForResult(Intent(Intent.ACTION_CREATE_DOCUMENT).apply{type="application/pdf";addCategory(Intent.CATEGORY_OPENABLE);putExtra(Intent.EXTRA_TITLE,"EduNexa_Marksheet_${System.currentTimeMillis()}.pdf")},402)}};r.addView(save);status=TextView(this).apply{setPadding(0,16,0,20)};r.addView(status);setContentView(ScrollView(this).apply{addView(r)})}
 override fun onActivityResult(q:Int,res:Int,data:Intent?){super.onActivityResult(q,res,data);if(res!=Activity.RESULT_OK)return;if(q==401){logo=data?.data?.let{contentResolver.openInputStream(it)?.use(BitmapFactory::decodeStream)};status.text="School logo selected"}else if(q==402){val uri=data?.data?:return;val bmp=sheet?:return;val pdf=PdfDocument();val pg=pdf.startPage(PdfDocument.PageInfo.Builder(bmp.width,bmp.height,1).create());pg.canvas.drawBitmap(bmp,0f,0f,null);pdf.finishPage(pg);runCatching{contentResolver.openOutputStream(uri)?.use{pdf.writeTo(it)};unsaved=false;status.text="Marksheet PDF saved successfully"}.onFailure{status.text="Save failed: ${it.message}"};pdf.close()}}
 private fun generate(){if(school.text.isBlank()||student.text.isBlank()||subjects.text.isBlank()){status.text="Enter school, student and subject marks";return};val rows=parseSubjects();if(rows.isEmpty()){status.text="Use format: Math:100:80, Hindi:100:70";return};val id="EDX-"+UUID.randomUUID().toString().take(8).uppercase();val maxTotal=rows.sumOf{it.second};val gotTotal=rows.sumOf{it.third};val pct=if(maxTotal>0)gotTotal*100.0/maxTotal else 0.0;val result=if(rows.all{it.third*100/it.second>=33})"PASS" else "FAIL";val qrPayload="EDUNEXA|ID=$id|SCHOOL=${school.text}|STUDENT=${student.text}|ROLL=${roll.text}|CLASS=${clazz.text}|EXAM=${exam.text}|SESSION=${session.text}|TOTAL=$gotTotal/$maxTotal|PERCENT=%.2f|RESULT=$result".format(pct);val w=1240;val h=1754;val b=Bitmap.createBitmap(w,h,Bitmap.Config.ARGB_8888);val c=Canvas(b);c.drawColor(Color.WHITE);val p=Paint(1).apply{color=Color.rgb(25,45,90)};c.drawRect(0f,0f,w.toFloat(),18f,p);p.textAlign=Paint.Align.CENTER;p.typeface=Typeface.DEFAULT_BOLD;p.textSize=54f;c.drawText(school.text.toString(),w/2f,105f,p);p.textSize=25f;p.typeface=Typeface.DEFAULT;c.drawText(address.text.toString(),w/2f,145f,p);logo?.let{c.drawBitmap(Bitmap.createScaledBitmap(it,120,120,true),55f,45f,null)};p.typeface=Typeface.DEFAULT_BOLD;p.textSize=36f;c.drawText("ACADEMIC MARKSHEET",w/2f,215f,p);p.textAlign=Paint.Align.LEFT;p.textSize=25f;p.typeface=Typeface.DEFAULT;c.drawText("Student: ${student.text}",65f,285f,p);c.drawText("Roll/Admission: ${roll.text}",650f,285f,p);c.drawText("Class: ${clazz.text}",65f,330f,p);c.drawText("Exam: ${exam.text}   Session: ${session.text}",650f,330f,p);var y=410f;p.typeface=Typeface.DEFAULT_BOLD;c.drawText("SUBJECT",70f,y,p);c.drawText("MAX",650f,y,p);c.drawText("OBTAINED",820f,y,p);c.drawText("GRADE",1040f,y,p);p.typeface=Typeface.DEFAULT;rows.forEach{(n,m,g)->y+=55;c.drawText(n,70f,y,p);c.drawText(m.toString(),650f,y,p);c.drawText(g.toString(),820f,y,p);c.drawText(grade(g,m),1040f,y,p)};y+=90;p.typeface=Typeface.DEFAULT_BOLD;p.textSize=29f;c.drawText("Total: $gotTotal / $maxTotal",70f,y,p);c.drawText("Percentage: %.2f%%".format(pct),430f,y,p);c.drawText("Result: $result",850f,y,p);val qr=makeQr(qrPayload,230);c.drawBitmap(qr,70f,h-430f,null);p.typeface=Typeface.DEFAULT;p.textSize=21f;c.drawText("Scan to read verification data",320f,h-350f,p);c.drawText("Verification ID: $id",320f,h-310f,p);c.drawText("Class Teacher Signature",70f,h-150f,p);c.drawText("School Stamp",500f,h-150f,p);c.drawText("Principal Signature",900f,h-150f,p);p.textAlign=Paint.Align.CENTER;p.textSize=18f;c.drawText("EduNexa marksheet • QR contains verification data",w/2f,h-65f,p);sheet=b;preview.setImageBitmap(b);preview.visibility=View.VISIBLE;save.visibility=View.VISIBLE;unsaved=true;status.text="Preview ready • QR active • Verification ID: $id • Nothing saved yet."}
 private fun makeQr(text:String,size:Int):Bitmap{val matrix=QRCodeWriter().encode(text,BarcodeFormat.QR_CODE,size,size);return Bitmap.createBitmap(size,size,Bitmap.Config.RGB_565).apply{for(x in 0 until size)for(y in 0 until size)setPixel(x,y,if(matrix[x,y])Color.BLACK else Color.WHITE)}}
 private fun parseSubjects():List<Triple<String,Int,Int>> = subjects.text.toString().split(',').mapNotNull{val x=it.trim().split(':');if(x.size==3){val m=x[1].toIntOrNull();val g=x[2].toIntOrNull();if(m!=null&&g!=null&&m>0&&g in 0..m)Triple(x[0].trim(),m,g)else null}else null}
 private fun grade(g:Int,m:Int)=when(g*100/m){in 90..100->"A+";in 80..89->"A";in 70..79->"B+";in 60..69->"B";in 50..59->"C";in 33..49->"D";else->"F"}
 override fun onBackPressed(){if(unsaved)AlertDialog.Builder(this).setTitle("Discard unsaved marksheet?").setMessage("The preview has not been saved.").setPositiveButton("Discard"){_,_->unsaved=false;super.onBackPressed()}.setNegativeButton("Stay",null).show()else super.onBackPressed()}
}
