package com.edunexa.app
import android.app.Activity
import android.content.*
import android.graphics.BitmapFactory
import android.os.Bundle
import android.provider.MediaStore
import android.widget.*
import androidx.appcompat.app.AppCompatActivity
class PhotoSignatureToolActivity:AppCompatActivity(){private lateinit var w:EditText;private lateinit var h:EditText;private lateinit var status:TextView;override fun onCreate(b:Bundle?){super.onCreate(b);val r=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(36,36,36,36)};r.addView(TextView(this).apply{text="Exam Form Photo & Signature Maker";textSize=24f;setTypeface(typeface,1)});w=EditText(this).apply{hint="Width px (example 300)";inputType=2};h=EditText(this).apply{hint="Height px (example 400)";inputType=2};status=TextView(this);r.addView(w);r.addView(h);r.addView(Button(this).apply{text="Select & Create";setOnClickListener{startActivityForResult(Intent(Intent.ACTION_PICK,MediaStore.Images.Media.EXTERNAL_CONTENT_URI),81)}});r.addView(status);setContentView(r)}
override fun onActivityResult(q:Int,res:Int,data:Intent?){super.onActivityResult(q,res,data);if(q!=81||res!=Activity.RESULT_OK)return;val width=w.text.toString().toIntOrNull();val height=h.text.toString().toIntOrNull();if(width==null||height==null||width<1||height<1){status.text="Enter valid width and height";return};val u=data?.data?:return;val bmp=contentResolver.openInputStream(u)?.use{BitmapFactory.decodeStream(it)}?:return;val out=android.graphics.Bitmap.createScaledBitmap(bmp,width,height,true);val name="EduNexa_Form_${System.currentTimeMillis()}.jpg";val values=ContentValues().apply{put(MediaStore.Images.Media.DISPLAY_NAME,name);put(MediaStore.Images.Media.MIME_TYPE,"image/jpeg")};contentResolver.insert(MediaStore.Images.Media.EXTERNAL_CONTENT_URI,values)?.let{x->contentResolver.openOutputStream(x)?.use{out.compress(android.graphics.Bitmap.CompressFormat.JPEG,92,it)};status.text="Created ${width}×${height}px • Saved as $name"}?:run{status.text="Save failed"}}}
