package com.edunexa.app

import android.os.Bundle
import android.view.View
import android.widget.*
import androidx.appcompat.app.AppCompatActivity
import com.edunexa.app.data.McqRepository

class PublishMcqActivity:AppCompatActivity(){private val repo=McqRepository();private val questions=mutableListOf<Map<String,Any>>();override fun onCreate(savedInstanceState:Bundle?){super.onCreate(savedInstanceState);setContentView(R.layout.activity_publish_mcq);val title=findViewById<EditText>(R.id.testTitleInput);val subject=findViewById<EditText>(R.id.testSubjectInput);val chapter=findViewById<EditText>(R.id.testChapterInput);val duration=findViewById<EditText>(R.id.testDurationInput);val question=findViewById<EditText>(R.id.questionInput);val a=findViewById<EditText>(R.id.optionAInput);val b=findViewById<EditText>(R.id.optionBInput);val c=findViewById<EditText>(R.id.optionCInput);val d=findViewById<EditText>(R.id.optionDInput);val explanation=findViewById<EditText>(R.id.explanationInput);val correct=findViewById<Spinner>(R.id.correctOptionSpinner);correct.adapter=ArrayAdapter(this,android.R.layout.simple_spinner_dropdown_item,listOf("Correct: A","Correct: B","Correct: C","Correct: D"));val count=findViewById<TextView>(R.id.questionCountText);val status=findViewById<TextView>(R.id.testStatus);val progress=findViewById<ProgressBar>(R.id.testProgress);fun addQuestion():Boolean{if(question.text.isBlank()||a.text.isBlank()||b.text.isBlank()||c.text.isBlank()||d.text.isBlank()){status.text="Complete the current question";return false};questions.add(mapOf("question" to question.text.toString().trim(),"options" to listOf(a.text.toString().trim(),b.text.toString().trim(),c.text.toString().trim(),d.text.toString().trim()),"correctIndex" to correct.selectedItemPosition,"explanation" to explanation.text.toString().trim()));question.text.clear();a.text.clear();b.text.clear();c.text.clear();d.text.clear();explanation.text.clear();correct.setSelection(0);count.text="Question ${questions.size+1} • ${questions.size} added";status.text="Question ${questions.size} added";return true};findViewById<Button>(R.id.addQuestionBtn).setOnClickListener{addQuestion()};val publish=findViewById<Button>(R.id.publishTestBtn);publish.setOnClickListener{if(title.text.isBlank()||subject.text.isBlank()){status.text="Enter test title and subject";return@setOnClickListener};if(question.text.isNotBlank()&&!addQuestion())return@setOnClickListener;if(questions.isEmpty()){status.text="Add at least one question";return@setOnClickListener};publish.isEnabled=false;progress.visibility=View.VISIBLE;status.text="Publishing test…";repo.publishTest(title.text.toString(),subject.text.toString(),chapter.text.toString(),duration.text.toString().toIntOrNull()?:10,questions.toList()){ok,msg->progress.visibility=View.GONE;publish.isEnabled=true;status.text=msg;if(ok){questions.clear();count.text="Question 1 • 0 added"}}}}}
