package com.edunexa.app
import android.content.Intent
import android.os.Bundle
import android.widget.Button
import android.widget.Toast
import androidx.appcompat.app.AppCompatActivity
import com.google.firebase.auth.FirebaseAuth
import com.google.firebase.firestore.FirebaseFirestore
class SchoolActivity:AppCompatActivity(){private val db=FirebaseFirestore.getInstance();override fun onCreate(savedInstanceState:Bundle?){super.onCreate(savedInstanceState);setContentView(R.layout.activity_school);verifySchool();findViewById<Button>(R.id.studentsBtn).setOnClickListener{startActivity(Intent(this,StudentManagementActivity::class.java))};findViewById<Button>(R.id.resultsBtn).setOnClickListener{startActivity(Intent(this,PublishResultActivity::class.java))};findViewById<Button>(R.id.mcqBtn).setOnClickListener{startActivity(Intent(this,PublishMcqActivity::class.java))};findViewById<Button>(R.id.attendanceBtn).setOnClickListener{startActivity(Intent(this,AttendanceActivity::class.java))};findViewById<Button>(R.id.announcementBtn).setOnClickListener{startActivity(Intent(this,PublishNoticeActivity::class.java))};findViewById<Button>(R.id.toolsBtn).setOnClickListener{startActivity(Intent(this,ToolsActivity::class.java))};findViewById<Button>(R.id.logoutBtn).setOnClickListener{FirebaseAuth.getInstance().signOut();startActivity(Intent(this,AuthActivity::class.java).apply{flags=Intent.FLAG_ACTIVITY_NEW_TASK or Intent.FLAG_ACTIVITY_CLEAR_TASK});finish()}}private fun verifySchool(){val uid=FirebaseAuth.getInstance().currentUser?.uid?:return finish();db.collection("users").document(uid).get().addOnSuccessListener{d->if(d.getString("role")!="school"||d.getBoolean("schoolApproved")!=true){Toast.makeText(this,"School services require admin approval",Toast.LENGTH_LONG).show();finish()}}.addOnFailureListener{finish()}}}
